sc delete _Account
sc delete _AccountLog
sc delete _Login
sc delete _Character
sc delete _GameLog
sc delete _WorldManager
sc delete _GamigoZR
sc delete _Zone0
sc delete _Zone1
sc delete _Zone2
sc delete _Zone3
sc delete _Zone4