sc stop _Account
sc stop _AccountLog
sc stop _Login
sc stop _Character
sc stop _GameLog
sc stop _WorldManager
sc stop _GamigoZR
sc stop _Zone0
sc stop _Zone1
sc stop _Zone2
sc stop _Zone3
sc stop _Zone4
TIMEOUT /T 5
sc start _Account
sc start _AccountLog
sc start _Login
sc start _Character
sc start _GameLog
sc start _WorldManager
sc start _GamigoZR
TIMEOUT /T 5
sc start _Zone0
sc start _Zone1
sc start _Zone2
sc start _Zone3
sc start _Zone4