sc start _Account
sc start _AccountLog
sc start _Login
sc start _Character
sc start _GameLog
sc start _WorldManager
sc start _GamigoZR
TIMEOUT /T 5
sc start _Zone0
sc start _Zone1
sc start _Zone2
sc start _Zone3
sc start _Zone4